version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: xroutr
      POSTGRES_PASSWORD: xroutr
      POSTGRES_DB: xroutr
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports: ["1025:1025", "8025:8025"]
  backend:
    build:
      context: ../backend
      dockerfile: ../infra/Dockerfile.backend
    environment:
      BFF_BACKEND_URL: http://backend:8000
    ports: ["8000:8000"]
    depends_on: [postgres, redis]
  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile.frontend
    environment:
      BFF_BACKEND_URL: http://backend:8000
    ports: ["3000:3000"]
    depends_on: [backend]

